### ISSUE TITLE
Make new excel output 

### ISSUE THREAD

**Issue by VadimPutsick** [VadimPutsick/ziv#1]
New entity to output is order. 
Method orderCreator.createOrder return order list. 
It is necessary to write order list in Excel.
![image](https://user-images.githubusercontent.com/25910525/70997141-6312d680-20e5-11ea-84bf-0336333660b9.png)
Field needed to output:

- Order №(order index in order list)
- Width (use getOrderCommonInfos to get CommonInfos list)
- Count (use getOrderCommonInfos to get CommonInfos list)
- Roll Count
- Waste

Attention!!!
Last element in order list is remnants:
![image](https://user-images.githubusercontent.com/25910525/70997642-999d2100-20e6-11ea-9c05-2532952a386f.png)
In output:
- Order № - остатки
- Width (use getOrderCommonInfos to get CommonInfos list)
- Count (use getOrderCommonInfos to get CommonInfos list)
Fields  Roll Count, Waste  are empty

**Comment by SHIROKEY** [comment]
Issue resolved with incoming pull request: #2 Review it and merge into master please

**Comment by VadimPutsick** [comment]
Good
